name: Fetch N2G MLS

# runs every day at 08:00 UTC + manual trigger
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch worksheets from SharePoint
        # 🔥 Hard-coded Azure creds below
        env:
          AZURE_CLIENT_ID:     "430ac0be-52d5-4562-ba2a-4739140e638f"
          AZURE_CLIENT_SECRET: "TWM8Q~srCA1PgMefilHpMRTLADqNkqWrMpAUOaXA"
          AZURE_TENANT_ID:     "d72741b9-6bf4-4282-8dfd-0af4f56d4023"
        run: |
          python mlsfetcher.py

      - name: Upload MLS CSV
        uses: actions/upload-artifact@v3
        with:
          name: master-location-sheet
          path: master_location_sheet.csv
